server:
  port: 9998
spring:
  application:
    name: euraka-server-01

eureka:
  instance:
    appname: euraka-server-01
    prefer-ip-address: true
    hostname: euraka-server-01
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/,http://localhost:9998/eureka/
    fetch-registry: false
    register-with-eureka: false
    registry-fetch-interval-seconds: 5
  server:
    # 设为false，关闭自我保护
    enable-self-preservation: false
    # 清理间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 10000

logging:
  file: log/euraka-server-01.log
  level:
    cn.imacoder.eurakaclient01: info
