server:
  port: 8080
spring:
  application:
    name: euraka-client-01

eureka:
  instance:
    appname: euraka-client-01
    #prefer-ip-address: true
    hostname: localhost
    #instance-id: euraka-client-01
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/,http://localhost:9998/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  file: log/euraka-client-01.log
  level:
    cn.imacoder.eurakaclient01: info
