server:
  port: 8081  # ${random.int[2000,8000]}
spring:
  application:
    name: euraka-client-02

eureka:
  instance:
    appname: euraka-client-02
    #prefer-ip-address: true
    hostname: localhost
    #instance-id: euraka-client-02_
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/,http://localhost:9998/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5

logging:
  file: log/euraka-client-02.log
  level:
    cn.imacoder.eurakaclient01: info
