server:
  port: 9999
spring:
  application:
    name: euraka-server-02

eureka:
  instance:
    appname: euraka-server-02
    prefer-ip-address: true
    hostname: euraka-server-02
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/,http://localhost:9998/eureka/
    fetch-registry: false
    register-with-eureka: false

logging:
  file: log/euraka-server-02.log
  level:
    cn.imacoder.eurakaclient01: info
